### ISSUE TITLE
Postgres v.14 + Patroni v.2

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-postgres#105]
Upgrade of the cas-postgres docker image in our playground namespace went seamlessly, without requiring any manual intervention.

To increase confidence that this will not impact production data, upgrading should first be done for non-critical applications. Suggesting the following order:

1. shipit
1. airflow
1. ggircs
1. metabase
1. ciip

**Comment by rdromey** [comment]
Work completed, good to close.
