### ISSUE TITLE
Reusable patroni chart

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-postgres#116]
### Description
@kuanfandevops wants to reuse our patroni helm chart, but it needs some changes to fit his use case (which is similar to many other teams across the org).

The use case is continuous archiving in a PVC, which can be supported by adding chart options to deploy a minio pod and a PVC along the patroni statefulset. The statefulset template also need to be updated to support loading the minio credentials from a secret. 

For this work, we should start by moving the patroni chart to a new `patroni-chart` repository, to encourage reuse and contributions from other teams. The `cas-postgres` chart, containing features specifically used by the CAS team (google cloud storage buckets provisioning), should stay in this repository

**Comment by matthieu-foucault** [comment]
@LindsayMacfarlane @pbastia @dleard to support Kuan with his timeline and allow our team's work to be reused, we should schedule this technical debt item in our upcoming sprint

**Comment by pbastia** [comment]
I second this :)
